// Header actions
export const SEARCHED_WORD_CHANGED = "SEARCHED_WORD_CHANGED";

// WordContainer actions
export const FETCH_WORDS_START = "FETCH_WORDS_START";
export const FETCH_WORDS_SUCCESS = "FETCH_WORDS_SUCCESS";
export const FETCH_WORDS_FAIL = "FETCH_WORDS_FAIL";
export const CHANGE_FILTERED_WORDS = "CHANGE_FILTERED_WORDS";
export const FORM_START = "FORM_START";
export const CREATE_WORD_SUCCESS = "CREATE_WORD_SUCCESS";
export const EDIT_WORD_SUCCESS = "EDIT_WORD_SUCCESS"
export const DELETE_WORD_SUCCESS = "DELETE_WORD_SUCCESS";

// Authentication actions
export const AUTH_SUCCESS = "AUTH_SUCCESS";